### ISSUE TITLE
Error: OnServerInitialized

### ISSUE THREAD

**Issue by thakyZ** [umods/EnhancedBanSystem#2]
I am getting this error every time I start my server with version 5.2.1
https://pastebin.com/b71TS7Nx

**Comment by lukespragg** [comment]
From the error, it looks like you're missing the Player Database plugin.

**Comment by thakyZ** [comment]
Oh... Ok I will look into that, I could have sworn I had it.

**Comment by thakyZ** [comment]
(Updated)

**Comment by thakyZ** [comment]
I do seem to have the latest version already installed. Let me check the plugin data.

**Comment by thakyZ** [comment]
I do for sure have it installed and on version 1.5.7, with SQLite as the setting to store data.

**Comment by thakyZ** [comment]
I do store the PlayerDatabase.cs in the oxide/plugins folder right? Because that is exactly where I have it atm, and oxide seems to load the plugin fine from there.

**Comment by Slut** [comment]
@thakyZ can you please send me your PlayerDatabase plugin as Oxide is down and I cannot get a copy of it.

**Comment by thakyZ** [comment]
Ok one moment

**Comment by thakyZ** [comment]
Here you go.
[PlayerDatabase.zip](https://github.com/umods/EnhancedBanSystem/files/1754087/PlayerDatabase.zip)

**Comment by Slut** [comment]
Fixed
